# Generated by Django 6.0.1 on 2026-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField()),
                ('numero_compteur', models.CharField(max_length=20, unique=True)),
                ('type_abonnement', models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIEL', 'Industriel')], default='RESIDENTIEL', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_complet'],
            },
        ),
    ]
