# Generated by Django 6.0.1 on 2026-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('date_coupure', models.DateTimeField()),
                ('duree_estimee', models.IntegerField(help_text='Durée en minutes')),
                ('raison', models.TextField()),
                ('type_coupure', models.CharField(choices=[('MAINTENANCE', 'Maintenance programmée'), ('PANNE', 'Panne technique'), ('TRAVAUX', 'Travaux')], max_length=20)),
                ('terminee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coupure',
                'verbose_name_plural': 'Coupures',
                'ordering': ['-date_coupure'],
            },
        ),
    ]
