# Generated by Django 4.2.10 on 2026-02-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_client_id_alter_coupure_id_alter_facture_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='reclamations/'),
        ),
    ]
